import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const geistOutfit = Outfit({
  subsets: ["latin"],
  weight:["400","500","600","700"]
});

const geistOvo = Ovo({
  subsets: ["latin"],
  weight:["400"]
});

export const metadata: Metadata = {
  title: "Дядя Крон - Портфолио",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistOutfit.className} ${geistOvo.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
